name: Create and upload a SBOM to release assets
on:
  workflow_dispatch:
    types: [generate-sbom]
defaults:
  run:
    shell: pwsh
jobs:
create-sbom:
   needs: version-check
    runs-on:
    steps:
    #Installation    
      - name: Install SYFT tool on Windows
        if: ${{ runner.os == 'Windows' }}
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b D:/syft
      - name: Install SYFT tool on Ubuntu or macOS
        if: ${{ runner.os != 'Windows' }}
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin 
    #Run        
      - name: Run SYFT on Windows
        if: ${{ runner.os == 'Windows' }}
        run: D:/syft/syft dir:C:/ -vv -o spdx-json=sbom.json
      - name: Run SYFT on Ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: syft dir:/ -vv -o spdx-json=sbom.json
      - name: Run SYFT on macOS
        if: ${{ runner.os == 'macOS' }}
        run: syft dir:/ -vv -o spdx-json=sbom.json --exclude ./Users --exclude ./System/Volumes --exclude ./private        
    #Preparing artifact
      - name: Compress SBOM file
        run: Compress-Archive sbom.json sbom.json.zip
      - uses: actions/upload-artifact@v3
        with:
          name: sbom-testimage:latest
          path: sbom.json.zip        
