name: Ticket Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  ORG: knoldus Inc
  PROJECT_NAME: knoldus-leaderboard
  CODESQAUD_URL: https://www.getcodesquad.com/api/add/reports
  AUTHOR: Azmat Hasan (azmathasan92)

jobs:
  build_be:
    env:
      MODULE_NAME: leaderboard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    
    - name: Run test cases and generate reports
      working-directory: app
      env:
        URL: "jdbc:h2:mem:test;MODE=Oracle;"
        DRIVER: "org.h2.Driver"
#         USERNAME: 
#         PASSWORD: 
      run: |
        npm audit fix
        sudo timedatectl set-timezone Asia/Kolkata
        sbt cpd
        sbt scapegoat
        sbt scalastyle
        sbt coverage test coverageReport
        sbt sonarScan 
        
    - name: Run test cases and generate reports for Tech hub
      working-directory: ticket-service
      env:
        DATABASE: "test"
#         DB_USERNAME: 
#         DB_PASSWORD:
#         MAILER_PASSWORD: 
#         KNOLDUS_ACCESS_TOKEN: 
      run: |
        sudo timedatectl set-timezone Asia/Kolkata
        sbt cpd
        sbt scapegoat
        sbt scalastyle
        sbt coverage test coverageReport        
        sbt sonarScan 
  build_fe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
  
    - name: Cache Packages
      uses: actions/cache@v2
      with:
        path: |
          ui/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}

    - name: NPM Dependencies
      working-directory: ui
      run: |
        npm install
    
    - name: NPM test
      working-directory: ui
      run:
        npm run test-headless-coverage

    - name: Sonar coverage report
      if: github.event_name == 'push'
      working-directory: ui
      run:
        npm run sonar
